### ISSUE TITLE
如何在swagger-ui中使用header

### ISSUE THREAD

**Issue by oneone1995** [dyc87112/spring-boot-starter-swagger#13]
例如我使用```oauth2```认证，需要在```header```中带入```token```去请求数据，这如何在```swagger-ui```提供的页面中(即在浏览器中直接测试)，这给我带来了很大的困扰，需要认证的接口我只能通过```postman```去测试，搜索了很久也没有得到处理结果，因此想请教下

**Comment by dyc87112** [comment]
在页面中发起请求的时候加上header内容

**Comment by oneone1995** [comment]
![default](https://user-images.githubusercontent.com/12215935/29767843-8bf3479e-8c16-11e7-9035-edbb2c200f81.png)
感谢回复。页面上没有填写```header```的地方吧...是我没找到吗
