### ISSUE TITLE
properties中title中文乱码

### ISSUE THREAD

**Issue by Jafeyyu** [dyc87112/spring-boot-starter-swagger#22]
在properties配置title为中文，properties为utf-8编码，页面上中文标题乱码

**Comment by dyc87112** [comment]
非本starter问题。只给出建议，如还未解决，请再确认文件与编码与编辑器设置的是否一致。

参考IntelliJ的配置：
设置 File Encodings的Transparent native-to-ascii conversion为true，具体步骤如下：依次点击

File -> Settings -> Editor -> File Encodings

将Properties Files (*.properties)下的Default encoding for properties files设置为UTF-8，将Transparent native-to-ascii conversion前的勾选上。
