### ISSUE TITLE
增加group的配置支持

### ISSUE THREAD

**Issue by dyc87112** [dyc87112/spring-boot-starter-swagger#4]

**Comment by xhusky** [comment]
可否解释一下group的使用场景?
官方文档说明如下:
> A swagger group is a concept introduced by this library which is simply a unique identifier for a Swagger Resource Listing within your application. The reason this concept was introduced was to support applications which require more than one Resource Listing. Why would you need more than one Resource Listing? - A single Spring Web MVC application serves more than one API e.g. publicly facing and internally facing. - A single Spring Web MVC application serves multiple versions of the same API. e.g. v1 and v2
> In most cases an application will not need more than one Resource Listing and the concept of swagger groups can be ignored.

其中举了两个例子,
1. 一个应用服务于多个API,比如对外接口和对内接口
2. 一个应用服务于API 的多个版本,比如接口版本v1,v2...

是否可以理解成假设用base-path来区分API的两个版本group
v1 对应 /v1/**
v2 对应 /v2/**
- swagger.docket.v1.base-path=/v1/**
- swagger.docket.v2.base-path=/v2/**

**Comment by dyc87112** [comment]
可以这么玩~

**Comment by xhusky** [comment]
多谢 @dyc87112 那group一般会用于什么场景?
