### ISSUE TITLE
添加@EnableSwagger2Doc启动出现异常

### ISSUE THREAD

**Issue by juneryo** [dyc87112/spring-boot-starter-swagger#7]
1. 似乎是一定要设置debug=true？
如果不设置的话，会提示：

> To display the auto-configuration report re-run your application with 'debug' enabled.

是否可以考虑下不设置true，只是出现一个警告提示，而不是直接报错呢

2. 在设置debug=true之后，出现异常。。。

> Failed to start bean 'documentationPluginsBootstrapper'; nested exception is com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError

版本：1.2.0

**Comment by dyc87112** [comment]
未重现，可否提供一下报错的程序？

**Comment by juneryo** [comment]
我在测试项目中试了一下，没有报错。。。
实际开发中的项目中有这个异常。。。我先去掉一些依赖和配置，排查一下，先。

**Comment by juneryo** [comment]
问题查出来了。。。不是这边的原因。。。抱歉抱歉。。。
debug只是因为后续有异常，提示开启debug模式而已。。。
至于后面的异常，是因为controller方法中的参数中有ManyToMany的属性导致。。。
```
public CommonInfo<String> retrievePageList(
        @RequestParam Integer currentPage, 
        @RequestParam Integer pageSize, 
        @ModelAttribute Merchant entity,   // 这里有ManyToMany属性
        @ModelAttribute TimeRange range) {
        return "";
    }
```
话说这种情况应该怎么处理。。。

**Comment by dyc87112** [comment]
好的，那我close啦，感谢支持~

**Comment by zengdingxin** [comment]
我遇到同样的问题使用@EnableSwagger2Doc报错，使用这个@EnableSwagger2注解不报错

**Comment by zengdingxin** [comment]
最后楼主怎么解决的？
